import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useNotion } from "../hooks/useNotion";
import styles from "../styles/Home.module.css";
import { PageItem } from "./api/database";

const Home: NextPage = () => {
  const { queryDatabase } = useNotion();
  const [list, setList] = useState<PageItem[]>([]);

  const query = useCallback(async () => {
    const data = await queryDatabase();
    console.log(data, "data");
    setList(data as unknown as PageItem[]);
  }, [queryDatabase]);

  useEffect(() => {
    query();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={query}>Refresh</button>

      <ul>
        {list?.map(({ title, date, url }, i) => (
          <li key={i}>
            <a href={url} target="_blank" rel="noreferrer">
              <h3>{title}</h3>
              <p>{date}</p>
            </a>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default Home;
